ueberauth/ueberauth

lib/ueberauth/strategies/helpers.ex
test/ueberauth_test.exs

On heroku we're getting a forwarded port of 443 -> 80 which makes the callback port incorrect (it's inserting a port 80 into a https url)

full_url in helpers is using the port of the connection to overwrite things like the callback_url

---

CHANGELOG.md
lib/ueberauth.ex

This PR allows for selecting _some_ of the providers on a per-plug call basis.
```elixir
plug Ueberauth # all providers - existing behaviour unchanged
```
VS
```elixir
plug Ueberauth, providers: [:identity, :slack], base_path: "/admin/auth"
```

Allow selecting some providers in the plug

---

lib/ueberauth/strategies/helpers.ex
test/ueberauth_test.exs

This change makes `callback_url` respect the `x-forwarded-proto` header if it exists. This ensures that https urls will be generated when the app is running on an http server behind and https proxy.

support x-forwarded-proto (behind an https proxy)

---

lib/ueberauth.ex
lib/ueberauth/strategies/helpers.ex

Following three warning is issued in Elixir v1.2.5.
```
lib/ueberauth.ex:187: warning: the variable "providers" is unsafe as it has been defined in a conditional clause, as part of a case/cond/receive/if/&&/||. Please rewrite the clauses so the value is explicitly returned. For example:
case int do
1 -> atom = :one
2 -> atom = :two
end
Can be rewritten as:
atom =
case int do
1 -> :one
2 -> :two
end
```
```
lib/ueberauth.ex:187: warning: variable name is unused
```
```
lib/ueberauth/strategies/helpers.ex:139: warning: default arguments in full_url/3 are never used
```

Fix compiler warning

---

lib/ueberauth.ex
test/ueberauth_test.exs

This is my attempt at solving the trailing slash issue, raised in issue #27.
It uses the `String.replace_trailing/3` function on the `:request_path` option, as well as stripping it from the incoming request, to make the strategy selection insensitive to trailing slashes.

Intercept requests with and without a trailing slash

---

lib/ueberauth.ex

Allow multiple configurations of a provider

---

.gitignore
lib/ueberauth.ex
lib/ueberauth/strategies/helpers.ex
test/ueberauth_test.exs

I added ability to specify :callback_params in settings for strategies 
```
config :ueberauth, Ueberauth,
providers: [
facebook: { Ueberauth.Strategy.Facebook, [callback_params: ["type", "user_role"]]} 
]
```
then add this extra param to login/sign-up links 
```
auth_path(@conn, :request, "facebook", type: "sign-in")
auth_path(@conn, :request, "twitter", user_role: "manager")
```
Tested on facebook twitter and VK strategies.

Allow to add extra params to callback_url

---

.travis.yml
mix.exs
mix.lock

This PR should make Travis green.
* Add elixir 1.6 to travis config
* Update exclude option to not use OTP 18.3 and Elixir 1.6 which is not supported
by Elixir 1.6
* Remove elixir 1.3 from travis build since it was dropped in the 0.5.0 release (https://github.com/ueberauth/ueberauth/commit/d648d8f3938f3e64923d381e243f887ed75bf427)

Make travis green. Update travis config to reflect minimum elixir version in mix.exs

---

lib/ueberauth/auth/info.ex

- The typespec was missing the image field.
- This MR fills it in.

fill in missing image in info typespec

---

lib/ueberauth/strategies/helpers.ex
lib/ueberauth/strategy.ex
mix.exs
mix.lock

- Upgrade dependencies
- One noticeable change is for `Plug ~> 1.5` the `except: [request_url: 1]` to avoid duplication import of the same function from `Plug.Conn`.
- Removed credo dependency on request by @doomspork

upgrade deps

---

lib/ueberauth.ex

`def module` becomes `defmodule`

Fix `defmodule` in documentation example

---

lib/ueberauth.ex

When building, if Ueberauth configuration isn't present in the
application environment an exception is now raised.

Added exception for missing configuration.

---

CHANGELOG.md
lib/ueberauth.ex
mix.exs

- When a router forwards traffic to another router, the conn will have it script name set.
- Read from it and override request / callback paths as well for good measure to accommodate umbrella structures.
This is a follow-up PR to address the scenario of per-app Ueberuath pipelines existing in an Umbrella app. Although configuration is loaded properly, in case the individual apps do not have individual Endpoints (instead, they just have Routers and a central Endpoint + Router forward traffic to them), then the incoming conn will have `script_name` set, which may or may not be reflected in configuration for each individual provider.
So for example, a Google Ueberauth provider will expect callbacks to hit `/auth/google/callback` by default although it may be hosted in an app whose Endpoint …

Fixed Ueberauth request not respecting Script Name

---

lib/ueberauth.ex
test/support/simple_provider.ex
test/ueberauth_test.exs

This should implement https://github.com/ueberauth/ueberauth/issues/90

Add API functions to allow dynamic providers

---

README.md

Note: I don't know how common it is to run old elixir version in the wild and what is the last version where it was necessary to add Ueberauth to the application list.
If you think it is necessary, I can also mention the extra step needed for old elixir version.

No need to add Ueberauth to the application list (#117)

---

lib/ueberauth.ex

This handles an issue when the route_prefix is not found in the request_path.
e.g. when 
```elixir
route_prefix = "/audit_logs"
conn.request_path = "/auth/github"
```
Then the route key incorrectly becomes `//auth/github`.
This patch fixes it to ensure that it stays as `/auth/github`
For context, this situation arose from me setting my endpoint url.path to "/audit_logs", but using an ingress controller to rewrite the "/audit_logs" prefix out of all requests once it's forwarded to the application. This is due to phoenix sockets not using the endpoint path.

Fixed routing issue when route_prefix not in request_path

---

lib/ueberauth/strategy.ex

While investigating #121, I thought this was the culpit, unfortunately, this does not seem to resolve the issue, but I think we should still remove this duplication to avoid confusion in the future.

Remove dublicated call to handle_callback_result

---

.formatter.exs
.gitignore
CHANGELOG.md
README.md
lib/ueberauth.ex
lib/ueberauth/auth.ex
lib/ueberauth/auth/info.ex
lib/ueberauth/failure.ex
mix.exs

Besides other changes, this commit ensures the generated HTML doc for
HexDocs.pm will become the main source doc for this Elixir library which
leverage on ExDoc features.
List of changes:
* Use common source url
* Add changelog to html doc
* Add release date to changelog
* Update license section
* Badges and more badges!
* Fix typos
* Update gitignore
* Update formatter config
* Set output to html only
* Set and use latest ex_doc
* Follow minimum Elixir version with Travis CI

Misc doc generation changes

---

lib/ueberauth/strategy.ex
test/support/provider_with_csrf_attack_enabled.ex
test/ueberauth_test.exs

Hello,
In the https://github.com/ueberauth/ueberauth/pull/136 PR, we add a feature to protect CSRF attack by put the `state` parameter into cookie, and we remove the `state` cookie is after the `handle_callback!/1` function of the strategy in this changes, before this PR changes, in the `handle_callback!/1` function of the strategy we can do any proper process with Plug, but now we may see a similar "AlreadySentError" error if we make a redirection in the `handle_callback!/1`:
```
1) test make ensure run_callback properly clean the internal state param in cookie (UeberauthTest)
test/ueberauth_test.exs:233
** (Plug.Conn.AlreadySentError) the response was already sent
code: |> Ueberauth.run_callback(
stacktrace:
(plug 1.11.0) lib/plug/conn.ex:1720: Plug.Conn.update_cookies/2
(ueberauth …
```

Make a proper way to clean state cookie

---

lib/ueberauth/strategy.ex

💁 This change improves the readability of the documentation for configuring CSRF attack protection, which was previously added in #136.

Docs: CSRF attack configuration

---

CHANGELOG.md
lib/ueberauth.ex
lib/ueberauth/strategies/helpers.ex
mix.exs
test/ueberauth_test.exs

In our scenario, we cannot support `X-Forwarded-Proto` header due to network and security constrains related to our business case, therefore, we'd like to have the option to use a custom `https` scheme for callbacks instead
I think this is also related to https://github.com/ueberauth/ueberauth/issues/103 and https://github.com/ueberauth/ueberauth/issues/65
So, for now I'll just add a custom scheme option, but if and when this PR is approved and merged, I'd like to also add a custom port option, to better solve the issue aforementioned

Add custom URL resolution scheme option

---

lib/ueberauth.ex
lib/ueberauth/strategies/helpers.ex
test/ueberauth_test.exs

Related to changes: https://github.com/ueberauth/ueberauth/pull/144
Also relates to issues #103 and #65
This adds a custom port option
Should I also add a host option to have the full URL configurable, wdyt?

Add custom URL resolution port option

---

CHANGELOG.md
lib/ueberauth/strategies/helpers.ex
mix.exs
test/ueberauth_test.exs

This feature is similar to PR #14 that added support for differing port for apps behind proxies. 
We recently moved [our app](https://github.com/thechangelog/changelog.com) from Linode to Fly, which broke Ueberauth because the callback URL that gets generated uses the Fly app domain instead of our public [changelog.com](https://changelog.com) domain.
I have deployed and tested this change in production and confirmed it fixes the issue for us and you can sign in/up via Twitter and GitHub once again.

Prefer `x-forwarded-host` to construct callback_url

---

CHANGELOG.md
lib/ueberauth/strategy.ex
mix.exs
test/support/provider_with_custom_cookie_same_site.ex
test/ueberauth_test.exs

This PR adds a strategy option to change the SameSite value of the state param cookie.
Changing the same_site is required in certain scenarios like doing OAuth in an iframe.
see https://github.com/ueberauth/ueberauth/issues/148

Add option for state param cookie SameSite

---

CHANGELOG.md
lib/ueberauth/strategy.ex
mix.exs
test/ueberauth_test.exs

The `Ueberauth.Failure.Error` struct defines a type specification that
says that the `message_key` field should be a binary, however in the case of
CSRF attacks the `Ueberauth.Strategy` sets the error's `message_key` to
`:csrf_attack`. Whilst this does not cause problems in the way this
library works, it causes discrepancies in the way client code has to
handle errors. Ueberauth extensions such as `Ueberauth.Google` follow
the correct type specification and use binaries for `message_key`, so
client code needs to be able to pattern match against different types
which is not ideal.

Update :csrf_attack to "csrf_attack"

---

.github/workflows/ci.yml
CHANGELOG.md
lib/ueberauth/strategies/helpers.ex
mix.exs
test/ueberauth_test.exs

When a Phoenix web app is behind a reverse proxy, the redirect URL may come from the `X-Forwarded-Host` header. While ueberauth does this correctly, it only works on standard ports (80 and 443) and fails if e.g. using a localhost proxy on a non-standard port.
Set up Caddy or a reverse proxy of your choice that listens on a non-standard port, e.g. 8080
Configure Phoenix via `dev.exs` to serve from port 4000, but to know that the real site is port 8080.
When a redirect is done (e.g. via Google oauth), the `X-Forwarded-Host` will be `"localhost:8080"`
* note the port number in the host header, which is legal per the [MDN definition of host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host)
* but the `port` value in `helpers.ex` will *also* be set to `8080`
This results in …

Use or strip port from forwarded host header

---

CHANGELOG.md
lib/ueberauth/strategies/helpers.ex
mix.exs
test/ueberauth_test.exs

Cowboy will automatically default to port 80 when no port has been given, but Bandit does not. Bandit will always default to the underlying port, which makes it hard to know if there was a port specified or if a port was assumed.
This change ignores cowboy or bandit's assumption around port number and parses it from the header directly.
This solves: https://github.com/ueberauth/ueberauth/issues/180

Handle default ports when the host header has no port specified

---

lib/ueberauth/strategies/helpers.ex

The function from_private/2 can either return a value or nil. The
issue was found when doing a conditional check on the result of the
options function in ueberauth_cognito:
if opts = options(conn) do
Keyword.get(opts, :otp_app, default_app)
else
default_app
end
saying that it can never return nil, which is incorrect: 
```elixir
defp from_private(conn, key) do
opts = conn.private[:ueberauth_request_options]
if opts, do: opts[key], else: nil
end
```

Fix typespec for Helpers.options/1

---

README.md

This pull request provides an example to get started, including controller actions, right in the README. Doing so today requires finding the provider, following the steps, and then going to the example app to find the proper controller+action example. The goal is to streamline a complete step by step here.
We also mention `mix phx.gen.auth`, which is how most users will likely have setup their authentication.
Thank you <3

Streamline the onboarding experience

---

README.md

I noticed a small error in the project README that mentions a non-existing module

Readme: Fix module name in example
