ueberauth/ueberauth

- README.md
- lib/ueberauth.ex
- lib/ueberauth/strategies/helpers.ex
- lib/ueberauth/strategy.ex
- test/support/spec_router.exs
This addresses #4 
@chrismccord, thoughts?
> remove plug macro for normal plug

- lib/ueberauth/auth.ex
- lib/ueberauth/auth/extra.ex
- lib/ueberauth/failure.ex
- lib/ueberauth/failure/error.ex
- lib/ueberauth/strategies/helpers.ex
- lib/ueberauth/strategy.ex
This will make things tidier and easier to read.
> Fixup documentation widths

- README.md
Fixes a simple markdown error in the README.
> Fix link to Guardian in README

- lib/ueberauth/strategies/helpers.ex
There is no `Plug.t` spec so I have changed it to `Plug.Conn.t`
> Fixed plug conn specs

- lib/ueberauth/auth.ex
- lib/ueberauth/failure.ex
- lib/ueberauth/strategies/helpers.ex
Found some more spec mistakes :)
> Changed Module.t spec to module()

- lib/ueberauth.ex
- lib/ueberauth/strategies/helpers.ex
- mix.lock
Solves problems described at https://github.com/ueberauth/ueberauth/issues/18.
> Allow config of redirect_uri

- README.md
Since 0.4 is out, I guess it'd be nice to assist copy-pasta people :)
> Update README to use latest version

- lib/ueberauth/auth/info.ex
- lib/ueberauth/strategies/helpers.ex
- lib/ueberauth/strategy.ex
- mix.exs
- mix.lock
By request from @doomspork.
This simply adds it to the project and deals with any nags that came from running it (not in strict mode, though)
> Add Credo to Project

- config/test.exs
- lib/ueberauth.ex
- test/support/spec_router.exs
- test/ueberauth_test.exs
Fixes: https://github.com/ueberauth/ueberauth/issues/55
> Allow request and callback to use the same path but different http methods

- README.md
- Would be nice to have as badges
- links to docs
- current version
- license
> Add some more badges to readme

- .formatter.exs
- .travis.yml
- config/config.exs
- config/test.exs
- lib/ueberauth.ex
- lib/ueberauth/auth.ex
- lib/ueberauth/auth/credentials.ex
- lib/ueberauth/auth/extra.ex
- lib/ueberauth/auth/info.ex
- lib/ueberauth/failure.ex
- lib/ueberauth/failure/error.ex
- lib/ueberauth/strategies/helpers.ex
- lib/ueberauth/strategy.ex
- mix.exs
- test/support/mixins.exs
- test/support/spec_router.exs
- test/test_helper.exs
- test/ueberauth_test.exs
- Introduce elixir formatter for code standardization
- Not sure what the best settings for .formatter.exs are - any thoughts?
> introduce elixir formatter

- lib/ueberauth.ex
Hi
So this might be a problem because I just saw a refactoring PR (#85) in progress. But we needed per-app configuration any way, so if there is a way to merge both it will be great.
Thanks
> Refactored Ueberauth to support per-app configuration

- .travis.yml
- Makefile
- lib/ueberauth/strategies/helpers.ex
I'm going to bring all of our projects up-to-date with our CI configuration.
> Expand travis matrix and update Makefile

- lib/ueberauth.ex
- lib/ueberauth/strategy.ex
Cherry-picked the doc change from #129
> Improve docs

- README.md
Update README installation to  0.7
> Update README installation to  0.7

- lib/ueberauth/strategy.ex
> add default options callback to strategy

- lib/ueberauth/strategy.ex
- test/support/simple_provider.ex
Related to https://github.com/ueberauth/ueberauth/issues/150#issuecomment-1139692770
> Don't generate `auth/1` for every strategy

- CHANGELOG.md
- lib/ueberauth.ex
- mix.exs
- test/ueberauth_test.exs
Fixes https://github.com/ueberauth/ueberauth/issues/165
> Fix callback URL not mounted right when router has nested paths.

- CHANGELOG.md
- README.md
- lib/ueberauth.ex
- mix.exs
- test/ueberauth_test.exs
Reverts ueberauth/ueberauth#193
> Revert "Proposal of solution to #173"

- test/ueberauth_test.exs
> add unit test to validate returning 404 during the request phase
